replicaCount: 1

image:
  repository: armansheikhhosseini/go-web-app
  tag: 24906063480
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: ImplementationSpecific